; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using the MEGA Prototyper.
[ MEGAinfo ]
ver=0
[ DataSettings ]
datatype=snDistance
MissingBaseSymbol=?
IdenticalBaseSymbol=.
GapSymbol=-
[ ProcessTypes ]
ppInfer=true
ppNJ=true
[ AnalysisSettings ]
Analysis=Phylogeny Reconstruction
Scope=All Selected Taxa
Statistical Method=Neighbor-joining
